### ISSUE TITLE
Segfault on MSX

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#560]
Not sure if master is supposed to be stable or if it can be WIP between releases, but I got segfaults re: TMS9918 since you added a first to support PAL.

If this is expected, please close the issue!

```
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:299
#1  0x00005555556ab440 in Outputs::CRT::TextureBuilder::reduce_previous_allocation_to(unsigned long) ()
#2  0x00005555556a73a9 in Outputs::CRT::CRT::output_data(unsigned int, unsigned int) ()
#3  0x00005555555c4f8a in TI::TMS::TMS9918::run_for(HalfCycles) ()
#4  0x000055555567d4a8 in CPU::Z80::Processor<MSX::ConcreteMachine, false, false>::run_for(HalfCycles) ()
#5  0x0000555555680d4d in MSX::ConcreteMachine::run_for(Cycles) ()
#6  0x0000555555575c6a in (anonymous namespace)::BestEffortUpdaterDelegate::update(Concurrency::BestEffortUpdater*, double, bool) ()
#7  0x00005555555dad70 in std::_Function_handler<void (), Concurrency::BestEffortUpdater::update()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#8  0x00005555555d9ed2 in std::thread::_State_impl<std::_Bind_simple<Concurrency::AsyncTaskQueue::AsyncTaskQueue()::{lambda()#1} ()> >::_M_run() ()
#9  0x00007ffff714be6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff768d494 in start_thread (arg=0x7fffeea71700) at pthread_create.c:333
#11 0x00007ffff68c0acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by reidrac** [comment]
The PR fixes the issue on MSX for me, and I guess it may help in other machines too.
